version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build --prod
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install ncftp;
      - run:
          name: Send Via SFTP
          command: ncftp -R -v -u "${username}" ${host} VirusSimulator/ dist/VirusSimulator/*
  workflows:
    build-and-test:
      jobs:
        - build:
          filters:
            branches: 
              only: 
                -master
